1-module completed
js-tasks-ru/jsbasic-20230529_grinux pull request #2
Opened 2023-06-01 22:53 UTC by grinux84

1-module completed. Please check the coding style because I'm a C programmer.

2023-06-01 22:54 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-06-02 08:45 UTC, koalex requested changes
Несмотря на то, что тесты ОК нужно исправить замечания

2023-06-02 08:45 UTC, koalex commented on 1-module/1-task/index.js
> +  f = 1;
а где `let` ?

2023-06-02 08:45 UTC, koalex commented on 1-module/4-task/index.js
> +  for (i = 0; i < str.length; i++)
Здесь не нужен цикл для каждой буквы, можно сразу всю строку перевести в нижний регистр, вот так:
`let strLower = str.toLowerCase();`

2023-06-02 08:52 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-06-02 10:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2023-06-05 06:59 UTC, koalex approved these changes

2023-06-05 07:00 UTC, merged